{{- if .Values.agentmeshConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentmesh-proxy.fullname" . }}-config
  labels:
    {{- include "agentmesh-proxy.labels" . | nindent 4 }}
data:
  .agentmesh.yaml: |
    {{- .Values.agentmeshConfig | nindent 4 }}
{{- end }}
